### PR TITLE
Add TypeScript types definition.

### PR DESCRIPTION
**Pull request by petejohanson**
Library is working well for me, but I'm consuming from TypeScript.

Thoughts?

### CODE REVIEW

**Comment by rgrove** [comment]
Thanks!

Given that I can't commit to maintaining this definition myself, including it in this repo might mean it will eventually become out of date. Would it be better to include it here with that caveat, or to contribute it to http://definitelytyped.org/ as a version-specific definition?

**Comment by petejohanson** [comment]
I'm relatively new to the TS world, so I don't know that I can answer that question definitively. The advice on https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#create-a-new-package isn't particularly detailed on that point.

Ultimately, it can get distributed either way. The only potential upside to keeping it "in repo" would be allowing releases to be in sync. I'm not sure you're usual pace of changes/releases, but one option might be to include the definitions here, and when there are API changes, either I can see about setting up a watch that includes commits, or if you openned an issue here and assigned to me, I could work on updating the TS definition before your publish another version.

If you don't want to add that maintenance piece for this project (which I completely understand if that's the case), I'm happy to open a PR against the definitely typed repo.

Thanks again.

**Comment by petejohanson** [comment]
If you're curious, I'm leveraging `parse-xml` to handle the XML varient of the UBER hypermedia format in a library I'm in the early stages on: https://gitlab.com/petejohanson/hubris/blob/master/src/parsing/xml.ts

**Comment by rgrove** [comment]
It sounds like it would be best if you contributed this definition to DefinitelyTyped, since I'd prefer not to add the extra burden of maintaining the type definition here. Thanks though, and good luck with your project!

**Pull request closed without merging**
